### ISSUE TITLE
utils.Exp: 'errno:250, err:Authentication failed'

### ISSUE THREAD

**Issue by jeremyv1** [fusionstack/sdfs#5]
下载代码，执行test.py 返回
Traceback (most recent call last):
  File "test.py", line 583, in <module>
    test_exec(args)
  File "test.py", line 543, in test_exec
    test_init()
  File "test.py", line 511, in test_init
    cluster.create([socket.gethostname()])
  File "/home/mpsp/xujiaming/sdfs/admin/cluster.py", line 520, in create
    self._add_check_env(hosts)
  File "/home/mpsp/xujiaming/sdfs/admin/cluster.py", line 324, in _add_check_env
    exec_remote(host, cmd3)
  File "/home/mpsp/xujiaming/sdfs/admin/utils.py", line 417, in exec_remote
    password, timeout, exectimeout)
  File "/home/mpsp/xujiaming/sdfs/admin/utils.py", line 406, in _exec_remote
    raise Exp(250, 'Authentication failed')
utils.Exp: 'errno:250, err:Authentication failed'

有微信群或者QQ群 给解答一下么

**Comment by graydream** [comment]
似乎是本机的sshkey没有处理，先执行下
mkdir build
cd build
cmake ..
make install
/opt/sdfs/app/admin/cluster.py sshkey --hosts localhost
